# 1. Setup & Imports
This section imports required libraries, configures paths, and defines the experiment scope for FinSight XGBoost forecasting.

In [1]:
import sys
sys.path.append("../../../")

import json
from pathlib import Path

import joblib
import numpy as np
import optuna
import pandas as pd
import plotly.graph_objects as go
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.model_selection import TimeSeriesSplit
from xgboost import XGBRegressor

from backend.data.data_loader import fetch_stock_data
from backend.data.preprocessor import FinSightPreprocessor

optuna.logging.set_verbosity(optuna.logging.INFO)

TICKER = "HDFCBANK.NS"
START = "2020-01-01"
END = "2026-05-01"
TEST_START = "2025-01-01"

safe_ticker = ''.join(ch if ch.isalnum() else '_' for ch in TICKER)
ARTIFACTS_DIR = Path("./")
ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)

print(f"Ticker: {TICKER}")
print(f"Date range: {START} to {END}")
print(f"Artifacts dir: {ARTIFACTS_DIR.resolve()}")

c:\Users\gaura\Desktop\FinSight\finsightvenv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Ticker: HDFCBANK.NS
Date range: 2020-01-01 to 2026-05-01
Artifacts dir: C:\Users\gaura\Desktop\FinSight\notebooks\models\xgboost

# 2. Load Data
Load OHLCV data using FinSight's shared data loader and inspect shape and schema.

In [2]:
df = fetch_stock_data(TICKER, START, END)
print("Shape:", df.shape)
display(df.head())
df.info()

Shape: (1567, 9)

Price,Open,High,Low,Close,Volume,Adj Close,daily_return,log_return,hl_spread
Date,,,,,,,,,
2020-01-02,639.500000,644.000000,639.500000,643.375000,6137166,609.389160,0.006374,0.006354,4.500000
2020-01-03,641.099976,642.500000,631.799988,634.200012,10855550,600.698792,-0.014261,-0.014363,10.700012
2020-01-06,630.000000,630.900024,618.000000,620.474976,10890186,587.698853,-0.021641,-0.021879,12.900024
2020-01-07,629.450012,635.724976,626.125000,630.299988,14724494,597.004822,0.015835,0.015711,9.599976
2020-01-08,623.474976,631.075012,620.025024,628.650024,11332110,595.441956,-0.002618,-0.002621,11.049988

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1567 entries, 2020-01-02 to 2026-05-01
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          1567 non-null   float64
 1   High          1567 non-null   float64
 2   Low           1567 non-null   float64
 3   Close         1567 non-null   float64
 4   Volume        1567 non-null   int64
 5   Adj Close     1567 non-null   float64
 6   daily_return  1567 non-null   float64
 7   log_return    1567 non-null   float64
 8   hl_spread     1567 non-null   float64
dtypes: float64(8), int64(1)
memory usage: 122.4 KB

# 3. Feature Engineering
Apply FinSight preprocessing and optionally enrich the feature frame using graph features if the JSON artifact exists.
The target variable is next-day Close (`Close.shift(-1)`).

In [3]:
preprocessor = FinSightPreprocessor(ticker=TICKER)
processed_df = preprocessor.fit_transform(df)

graph_features_path = ARTIFACTS_DIR / "graph_features.json"
if graph_features_path.exists():
    with graph_features_path.open("r", encoding="utf-8") as f:
        graph_features = json.load(f)
    for k, v in graph_features.items():
        processed_df[k] = float(v)
    print(f"Loaded graph features from {graph_features_path}")
else:
    graph_features = {}
    print(f"No graph features found at {graph_features_path}; continuing without them.")

model_df = processed_df.copy()
model_df["target"] = model_df["Close"].shift(-1)
model_df = model_df.dropna(subset=["target"]).replace([np.inf, -np.inf], np.nan).dropna()

print("Final model frame shape:", model_df.shape)
display(model_df.head())
print("Feature columns (excluding target):", len([c for c in model_df.columns if c != "target"]))

No graph features found at graph_features.json; continuing without them.
Final model frame shape: (1547, 15)

,Open,High,Low,Close,Volume,Adj Close,daily_return,log_return,hl_spread,Close_lag_1,Close_lag_5,Close_lag_10,rolling_mean_20,rolling_std_20,target
Date,,,,,,,,,,,,,,,
2020-01-29,-1.277790,-1.271400,-1.224250,-1.233929,-0.545518,-1.240528,0.617558,0.620802,-0.608115,-1.282271,-1.207101,-1.030540,-1.141682,-0.666851,-1.272539
2020-01-30,-1.223918,-1.283469,-1.244035,-1.272539,-0.617486,-1.275065,-0.504253,-0.496689,-0.470182,-1.232459,-1.191381,-1.017203,-1.153743,-0.654015,-1.271554
2020-01-31,-1.253518,-1.288019,-1.232086,-1.271554,-0.657571,-1.274184,-0.004874,0.003287,-0.759839,-1.271048,-1.192560,-1.054468,-1.162108,-0.614829,-1.403536
2020-02-03,-1.389483,-1.445708,-1.398789,-1.403536,-0.576056,-1.392246,-1.694632,-1.705219,-0.573632,-1.270064,-1.315766,-1.145670,-1.171675,-0.434574,-1.257765
2020-02-04,-1.385536,-1.303056,-1.319257,-1.257765,-0.240307,-1.261849,1.887106,1.861340,0.512595,-1.401976,-1.276466,-1.187054,-1.177795,-0.416229,-1.199259

Feature columns (excluding target): 14

# 4. Train/Test Split
Create a chronological split with the last 20% as test data (no shuffling).

In [4]:
train_df = model_df[model_df.index < "2025-01-01"]
test_df = model_df[model_df.index >= "2025-01-01"]

feature_cols = [c for c in model_df.columns if c != "target"]
X_train, y_train = train_df[feature_cols], train_df["target"]
X_test, y_test = test_df[feature_cols], test_df["target"]

print("Train size:", len(train_df))
print("Test size:", len(test_df))
print("Features:", len(feature_cols))

Train size: 1218
Test size: 329
Features: 14

# 5. Time Series Cross Validation
Run baseline cross-validation using `TimeSeriesSplit(n_splits=5)` and report fold RMSE.

In [5]:
tscv = TimeSeriesSplit(n_splits=5)
baseline_rmses = []

for fold, (tr_idx, val_idx) in enumerate(tscv.split(X_train), start=1):
    X_tr, X_val = X_train.iloc[tr_idx], X_train.iloc[val_idx]
    y_tr, y_val = y_train.iloc[tr_idx], y_train.iloc[val_idx]

    model = XGBRegressor(
        n_estimators=500,
        learning_rate=0.05,
        max_depth=6,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        objective="reg:squarederror",
        tree_method="hist",
        device="cuda"
    )
    model.fit(X_tr, y_tr, eval_set=[(X_val, y_val)], verbose=100)

    preds = model.predict(X_val)
    rmse = float(np.sqrt(mean_squared_error(y_val, preds)))
    baseline_rmses.append(rmse)
    print(f"Fold {fold} RMSE: {rmse:.6f}")

print(f"Mean CV RMSE: {np.mean(baseline_rmses):.6f}")

[0]	validation_0-rmse:1.56331
[100]	validation_0-rmse:0.50011
[200]	validation_0-rmse:0.49275
[300]	validation_0-rmse:0.49397
[400]	validation_0-rmse:0.49433
[499]	validation_0-rmse:0.49442
Fold 1 RMSE: 0.494422
[0]	validation_0-rmse:0.81317

c:\Users\gaura\Desktop\FinSight\finsightvenv\lib\site-packages\xgboost\core.py:751: UserWarning: [20:55:25] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\common\error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)

[100]	validation_0-rmse:0.18242
[200]	validation_0-rmse:0.18382
[300]	validation_0-rmse:0.18437
[400]	validation_0-rmse:0.18415
[499]	validation_0-rmse:0.18441
Fold 2 RMSE: 0.184415
[0]	validation_0-rmse:0.88158
[100]	validation_0-rmse:0.11595
[200]	validation_0-rmse:0.11295
[300]	validation_0-rmse:0.11349
[400]	validation_0-rmse:0.11337
[499]	validation_0-rmse:0.11357
Fold 3 RMSE: 0.113574
[0]	validation_0-rmse:0.75363
[100]	validation_0-rmse:0.08497
[200]	validation_0-rmse:0.08991
[300]	validation_0-rmse:0.09150
[400]	validation_0-rmse:0.09202
[499]	validation_0-rmse:0.09251
Fold 4 RMSE: 0.092511
[0]	validation_0-rmse:0.88908
[100]	validation_0-rmse:0.26537
[200]	validation_0-rmse:0.26085
[300]	validation_0-rmse:0.26352
[400]	validation_0-rmse:0.26479
[499]	validation_0-rmse:0.26504
Fold 5 RMSE: 0.265039
Mean CV RMSE: 0.229992

# 6. Hyperparameter Tuning (Optuna)
Tune XGBoost hyperparameters with 50 Optuna trials using time-series CV and GPU execution.

In [6]:
def objective(trial: optuna.Trial) -> float:
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 100, 1000),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3),
        "max_depth": trial.suggest_int("max_depth", 3, 10),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
        "random_state": 42,
        "objective": "reg:squarederror",
        "tree_method": "hist",
        "device": "cuda"
    }

    cv = TimeSeriesSplit(n_splits=3)
    rmses = []
    for tr_idx, val_idx in cv.split(X_train):
        X_tr, X_val = X_train.iloc[tr_idx], X_train.iloc[val_idx]
        y_tr, y_val = y_train.iloc[tr_idx], y_train.iloc[val_idx]

        model = XGBRegressor(**params)
        model.fit(X_tr, y_tr, eval_set=[(X_val, y_val)], verbose=100)
        pred = model.predict(X_val)
        rmse = float(np.sqrt(mean_squared_error(y_val, pred)))
        rmses.append(rmse)

    print(f"Trial {trial.number} | RMSE: {float(np.mean(rmses)):.4f} | params: {trial.params}")
    return float(np.mean(rmses))

study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=20)

best_params = study.best_params
print("Best RMSE:", study.best_value)
print("Best params:")
for k, v in best_params.items():
    print(f"  {k}: {v}")

[I 2026-05-24 20:56:10,094] A new study created in memory with name: no-name-346b4044-6e8e-4250-bb1f-d9fe47260578

[0]	validation_0-rmse:0.89366
[100]	validation_0-rmse:0.15255
[200]	validation_0-rmse:0.15200
[300]	validation_0-rmse:0.15237
[332]	validation_0-rmse:0.15242
[0]	validation_0-rmse:0.81647
[100]	validation_0-rmse:0.09518
[200]	validation_0-rmse:0.09687
[300]	validation_0-rmse:0.09706
[332]	validation_0-rmse:0.09736
[0]	validation_0-rmse:0.71852
[100]	validation_0-rmse:0.20685
[200]	validation_0-rmse:0.20208
[300]	validation_0-rmse:0.20345
[332]	validation_0-rmse:0.20272

[I 2026-05-24 20:56:57,801] Trial 0 finished with value: 0.15083413864268513 and parameters: {'n_estimators': 333, 'learning_rate': 0.20399829315642912, 'max_depth': 5, 'subsample': 0.6773134255195675, 'colsample_bytree': 0.7220288818375744, 'min_child_weight': 7}. Best is trial 0 with value: 0.15083413864268513.

Trial 0 | RMSE: 0.1508 | params: {'n_estimators': 333, 'learning_rate': 0.20399829315642912, 'max_depth': 5, 'subsample': 0.6773134255195675, 'colsample_bytree': 0.7220288818375744, 'min_child_weight': 7}
[0]	validation_0-rmse:1.02346
[100]	validation_0-rmse:0.14073
[200]	validation_0-rmse:0.14191
[300]	validation_0-rmse:0.14182
[353]	validation_0-rmse:0.14181
[0]	validation_0-rmse:0.92144
[100]	validation_0-rmse:0.10893
[200]	validation_0-rmse:0.10908
[300]	validation_0-rmse:0.10924
[353]	validation_0-rmse:0.10928
[0]	validation_0-rmse:0.79979
[100]	validation_0-rmse:0.22413
[200]	validation_0-rmse:0.22602
[300]	validation_0-rmse:0.22617
[353]	validation_0-rmse:0.22619
Trial 1 | RMSE: 0.1591 | params: {'n_estimators': 354, 'learning_rate': 0.08096101432536228, 'max_depth': 10, 'subsample': 0.7857682471063876, 'colsample_bytree': 0.8870003147717049, 'min_child_weight': 2}

[I 2026-05-24 20:58:23,829] Trial 1 finished with value: 0.15909174573431215 and parameters: {'n_estimators': 354, 'learning_rate': 0.08096101432536228, 'max_depth': 10, 'subsample': 0.7857682471063876, 'colsample_bytree': 0.8870003147717049, 'min_child_weight': 2}. Best is trial 0 with value: 0.15083413864268513.

[0]	validation_0-rmse:0.89315
[100]	validation_0-rmse:0.15285
[200]	validation_0-rmse:0.15383
[300]	validation_0-rmse:0.15431
[400]	validation_0-rmse:0.15440
[500]	validation_0-rmse:0.15439
[600]	validation_0-rmse:0.15440
[700]	validation_0-rmse:0.15440
[796]	validation_0-rmse:0.15441
[0]	validation_0-rmse:0.81574
[100]	validation_0-rmse:0.09150
[200]	validation_0-rmse:0.09296
[300]	validation_0-rmse:0.09313
[400]	validation_0-rmse:0.09310
[500]	validation_0-rmse:0.09318
[600]	validation_0-rmse:0.09319
[700]	validation_0-rmse:0.09317
[796]	validation_0-rmse:0.09316
[0]	validation_0-rmse:0.71709
[100]	validation_0-rmse:0.19687
[200]	validation_0-rmse:0.19888
[300]	validation_0-rmse:0.19983
[400]	validation_0-rmse:0.20018
[500]	validation_0-rmse:0.20011
[600]	validation_0-rmse:0.20024
[700]	validation_0-rmse:0.20023
[796]	validation_0-rmse:0.20021

[I 2026-05-24 20:59:43,251] Trial 2 finished with value: 0.14926145340317395 and parameters: {'n_estimators': 797, 'learning_rate': 0.20306944058754628, 'max_depth': 6, 'subsample': 0.9269776941318035, 'colsample_bytree': 0.7918500814825957, 'min_child_weight': 9}. Best is trial 2 with value: 0.14926145340317395.

Trial 2 | RMSE: 0.1493 | params: {'n_estimators': 797, 'learning_rate': 0.20306944058754628, 'max_depth': 6, 'subsample': 0.9269776941318035, 'colsample_bytree': 0.7918500814825957, 'min_child_weight': 9}
[0]	validation_0-rmse:0.80655
[100]	validation_0-rmse:0.15216
[200]	validation_0-rmse:0.15612
[300]	validation_0-rmse:0.15638
[400]	validation_0-rmse:0.15649
[500]	validation_0-rmse:0.15669
[600]	validation_0-rmse:0.15674
[700]	validation_0-rmse:0.15674
[800]	validation_0-rmse:0.15675
[824]	validation_0-rmse:0.15674
[0]	validation_0-rmse:0.76330
[100]	validation_0-rmse:0.09704
[200]	validation_0-rmse:0.10436
[300]	validation_0-rmse:0.10633
[400]	validation_0-rmse:0.10618
[500]	validation_0-rmse:0.10668
[600]	validation_0-rmse:0.10682
[700]	validation_0-rmse:0.10714
[800]	validation_0-rmse:0.10708
[824]	validation_0-rmse:0.10707
[0]	validation_0-rmse:0.67257
[100]	validation_0-rmse:0.20584
[200]	validation_0-rmse:0.21347
[300]	validation_0-rmse:0.21291
[400]	validation_0-rmse:0.21589
[500]	validation_0-rmse:0.21681
[600]	validation_0-rmse:0.21667
[700]	validation_0-rmse:0.21711
[800]	validation_0-rmse:0.21743
[824]	validation_0-rmse:0.21748

[I 2026-05-24 21:00:44,847] Trial 3 finished with value: 0.16043212368842721 and parameters: {'n_estimators': 825, 'learning_rate': 0.2859018417242686, 'max_depth': 3, 'subsample': 0.8187293190799669, 'colsample_bytree': 0.6295117651821248, 'min_child_weight': 4}. Best is trial 2 with value: 0.14926145340317395.

Trial 3 | RMSE: 0.1604 | params: {'n_estimators': 825, 'learning_rate': 0.2859018417242686, 'max_depth': 3, 'subsample': 0.8187293190799669, 'colsample_bytree': 0.6295117651821248, 'min_child_weight': 4}
[0]	validation_0-rmse:1.00139
[100]	validation_0-rmse:0.14687
[200]	validation_0-rmse:0.14729
[300]	validation_0-rmse:0.14728
[400]	validation_0-rmse:0.14728
[500]	validation_0-rmse:0.14730
[600]	validation_0-rmse:0.14730
[700]	validation_0-rmse:0.14729
[800]	validation_0-rmse:0.14729
[897]	validation_0-rmse:0.14729
[0]	validation_0-rmse:0.90297
[100]	validation_0-rmse:0.09919
[200]	validation_0-rmse:0.09993
[300]	validation_0-rmse:0.09998
[400]	validation_0-rmse:0.09999
[500]	validation_0-rmse:0.10000
[600]	validation_0-rmse:0.10000
[700]	validation_0-rmse:0.10001
[800]	validation_0-rmse:0.09999
[897]	validation_0-rmse:0.10000
[0]	validation_0-rmse:0.78482
[100]	validation_0-rmse:0.22587
[200]	validation_0-rmse:0.22669
[300]	validation_0-rmse:0.22691
[400]	validation_0-rmse:0.22694
[500]	validation_0-rmse:0.22694
[600]	validation_0-rmse:0.22695
[700]	validation_0-rmse:0.22698
[800]	validation_0-rmse:0.22696
[897]	validation_0-rmse:0.22699

[I 2026-05-24 21:02:07,782] Trial 4 finished with value: 0.15809297499645322 and parameters: {'n_estimators': 898, 'learning_rate': 0.10222537354824685, 'max_depth': 9, 'subsample': 0.9123983212965752, 'colsample_bytree': 0.8462846688939166, 'min_child_weight': 3}. Best is trial 2 with value: 0.14926145340317395.

Trial 4 | RMSE: 0.1581 | params: {'n_estimators': 898, 'learning_rate': 0.10222537354824685, 'max_depth': 9, 'subsample': 0.9123983212965752, 'colsample_bytree': 0.8462846688939166, 'min_child_weight': 3}
[0]	validation_0-rmse:0.83670
[100]	validation_0-rmse:0.14915
[200]	validation_0-rmse:0.14950
[300]	validation_0-rmse:0.14999
[400]	validation_0-rmse:0.14991
[500]	validation_0-rmse:0.14995
[600]	validation_0-rmse:0.14995
[685]	validation_0-rmse:0.14998
[0]	validation_0-rmse:0.76777
[100]	validation_0-rmse:0.11487
[200]	validation_0-rmse:0.11384
[300]	validation_0-rmse:0.11363
[400]	validation_0-rmse:0.11370
[500]	validation_0-rmse:0.11381
[600]	validation_0-rmse:0.11380
[685]	validation_0-rmse:0.11382
[0]	validation_0-rmse:0.68218
[100]	validation_0-rmse:0.20451
[200]	validation_0-rmse:0.20819
[300]	validation_0-rmse:0.20855
[400]	validation_0-rmse:0.20885
[500]	validation_0-rmse:0.20893
[600]	validation_0-rmse:0.20895
[685]	validation_0-rmse:0.20899

[I 2026-05-24 21:03:55,488] Trial 5 finished with value: 0.15759617225212325 and parameters: {'n_estimators': 686, 'learning_rate': 0.25977084252150434, 'max_depth': 10, 'subsample': 0.6491645520988523, 'colsample_bytree': 0.622105211678741, 'min_child_weight': 10}. Best is trial 2 with value: 0.14926145340317395.

Trial 5 | RMSE: 0.1576 | params: {'n_estimators': 686, 'learning_rate': 0.25977084252150434, 'max_depth': 10, 'subsample': 0.6491645520988523, 'colsample_bytree': 0.622105211678741, 'min_child_weight': 10}
[0]	validation_0-rmse:0.96434
[100]	validation_0-rmse:0.14892
[200]	validation_0-rmse:0.15047
[210]	validation_0-rmse:0.15058
[0]	validation_0-rmse:0.87452
[100]	validation_0-rmse:0.09957
[200]	validation_0-rmse:0.10019
[210]	validation_0-rmse:0.10016
[0]	validation_0-rmse:0.76231
[100]	validation_0-rmse:0.20851
[200]	validation_0-rmse:0.21233
[210]	validation_0-rmse:0.21272

[I 2026-05-24 21:04:36,275] Trial 6 finished with value: 0.15448637540383917 and parameters: {'n_estimators': 211, 'learning_rate': 0.13608076422033696, 'max_depth': 8, 'subsample': 0.9809538232151032, 'colsample_bytree': 0.671658742641131, 'min_child_weight': 10}. Best is trial 2 with value: 0.14926145340317395.

Trial 6 | RMSE: 0.1545 | params: {'n_estimators': 211, 'learning_rate': 0.13608076422033696, 'max_depth': 8, 'subsample': 0.9809538232151032, 'colsample_bytree': 0.671658742641131, 'min_child_weight': 10}
[0]	validation_0-rmse:0.83637
[100]	validation_0-rmse:0.14257
[200]	validation_0-rmse:0.14262
[300]	validation_0-rmse:0.14261
[400]	validation_0-rmse:0.14262
[500]	validation_0-rmse:0.14262
[600]	validation_0-rmse:0.14262
[700]	validation_0-rmse:0.14262
[724]	validation_0-rmse:0.14262
[0]	validation_0-rmse:0.76666
[100]	validation_0-rmse:0.10283
[200]	validation_0-rmse:0.10382
[300]	validation_0-rmse:0.10377
[400]	validation_0-rmse:0.10375
[500]	validation_0-rmse:0.10374
[600]	validation_0-rmse:0.10375
[700]	validation_0-rmse:0.10376
[724]	validation_0-rmse:0.10376
[0]	validation_0-rmse:0.67820
[100]	validation_0-rmse:0.22563
[200]	validation_0-rmse:0.22553
[300]	validation_0-rmse:0.22523
[400]	validation_0-rmse:0.22523
[500]	validation_0-rmse:0.22521
[600]	validation_0-rmse:0.22522
[700]	validation_0-rmse:0.22523
[724]	validation_0-rmse:0.22523

[I 2026-05-24 21:05:28,762] Trial 7 finished with value: 0.15720258684726723 and parameters: {'n_estimators': 725, 'learning_rate': 0.26222701610567234, 'max_depth': 6, 'subsample': 0.6867796846940895, 'colsample_bytree': 0.8182815538949901, 'min_child_weight': 3}. Best is trial 2 with value: 0.14926145340317395.

Trial 7 | RMSE: 0.1572 | params: {'n_estimators': 725, 'learning_rate': 0.26222701610567234, 'max_depth': 6, 'subsample': 0.6867796846940895, 'colsample_bytree': 0.8182815538949901, 'min_child_weight': 3}
[0]	validation_0-rmse:0.89298
[100]	validation_0-rmse:0.14461
[200]	validation_0-rmse:0.14555
[300]	validation_0-rmse:0.14631
[400]	validation_0-rmse:0.14629
[492]	validation_0-rmse:0.14626
[0]	validation_0-rmse:0.81310
[100]	validation_0-rmse:0.09745
[200]	validation_0-rmse:0.09787
[300]	validation_0-rmse:0.09834
[400]	validation_0-rmse:0.09831
[492]	validation_0-rmse:0.09847
[0]	validation_0-rmse:0.71679
[100]	validation_0-rmse:0.20445
[200]	validation_0-rmse:0.20722
[300]	validation_0-rmse:0.20680
[400]	validation_0-rmse:0.20683
[492]	validation_0-rmse:0.20673
Trial 8 | RMSE: 0.1505 | params: {'n_estimators': 493, 'learning_rate': 0.20516155945585776, 'max_depth': 6, 'subsample': 0.8213996705047101, 'colsample_bytree': 0.6006109310237598, 'min_child_weight': 10}

[I 2026-05-24 21:06:33,651] Trial 8 finished with value: 0.15048953163739373 and parameters: {'n_estimators': 493, 'learning_rate': 0.20516155945585776, 'max_depth': 6, 'subsample': 0.8213996705047101, 'colsample_bytree': 0.6006109310237598, 'min_child_weight': 10}. Best is trial 2 with value: 0.14926145340317395.

[0]	validation_0-rmse:0.99764
[100]	validation_0-rmse:0.15260
[200]	validation_0-rmse:0.15307
[300]	validation_0-rmse:0.15308
[400]	validation_0-rmse:0.15306
[418]	validation_0-rmse:0.15306
[0]	validation_0-rmse:0.90278
[100]	validation_0-rmse:0.08823
[200]	validation_0-rmse:0.08863
[300]	validation_0-rmse:0.08874
[400]	validation_0-rmse:0.08871
[418]	validation_0-rmse:0.08871
[0]	validation_0-rmse:0.78345
[100]	validation_0-rmse:0.20255
[200]	validation_0-rmse:0.20524
[300]	validation_0-rmse:0.20512
[400]	validation_0-rmse:0.20521
[418]	validation_0-rmse:0.20521
Trial 9 | RMSE: 0.1490 | params: {'n_estimators': 419, 'learning_rate': 0.10421987318559679, 'max_depth': 10, 'subsample': 0.9199027939734449, 'colsample_bytree': 0.7429840042951529, 'min_child_weight': 5}

[I 2026-05-24 21:07:50,527] Trial 9 finished with value: 0.14899368373615926 and parameters: {'n_estimators': 419, 'learning_rate': 0.10421987318559679, 'max_depth': 10, 'subsample': 0.9199027939734449, 'colsample_bytree': 0.7429840042951529, 'min_child_weight': 5}. Best is trial 9 with value: 0.14899368373615926.

[0]	validation_0-rmse:1.09545
[100]	validation_0-rmse:0.34217
[130]	validation_0-rmse:0.25987
[0]	validation_0-rmse:0.98031
[100]	validation_0-rmse:0.30917
[130]	validation_0-rmse:0.22545
[0]	validation_0-rmse:0.84484
[100]	validation_0-rmse:0.35717
[130]	validation_0-rmse:0.30329

[I 2026-05-24 21:08:14,316] Trial 10 finished with value: 0.26286981934250075 and parameters: {'n_estimators': 131, 'learning_rate': 0.013249408554816058, 'max_depth': 8, 'subsample': 0.9047824653255161, 'colsample_bytree': 0.991176238509994, 'min_child_weight': 6}. Best is trial 9 with value: 0.14899368373615926.

Trial 10 | RMSE: 0.2629 | params: {'n_estimators': 131, 'learning_rate': 0.013249408554816058, 'max_depth': 8, 'subsample': 0.9047824653255161, 'colsample_bytree': 0.991176238509994, 'min_child_weight': 6}
[0]	validation_0-rmse:0.91709
[100]	validation_0-rmse:0.15155
[200]	validation_0-rmse:0.15370
[300]	validation_0-rmse:0.15426
[400]	validation_0-rmse:0.15466
[500]	validation_0-rmse:0.15480
[554]	validation_0-rmse:0.15481
[0]	validation_0-rmse:0.83720
[100]	validation_0-rmse:0.08725
[200]	validation_0-rmse:0.09031
[300]	validation_0-rmse:0.09199
[400]	validation_0-rmse:0.09283
[500]	validation_0-rmse:0.09336
[554]	validation_0-rmse:0.09340
[0]	validation_0-rmse:0.73348
[100]	validation_0-rmse:0.20538
[200]	validation_0-rmse:0.20900
[300]	validation_0-rmse:0.20768
[400]	validation_0-rmse:0.20736
[500]	validation_0-rmse:0.20847
[554]	validation_0-rmse:0.20904

[I 2026-05-24 21:09:04,039] Trial 11 finished with value: 0.15241558158039137 and parameters: {'n_estimators': 555, 'learning_rate': 0.1794979819256517, 'max_depth': 4, 'subsample': 0.9959878738508773, 'colsample_bytree': 0.741640493184198, 'min_child_weight': 7}. Best is trial 9 with value: 0.14899368373615926.

Trial 11 | RMSE: 0.1524 | params: {'n_estimators': 555, 'learning_rate': 0.1794979819256517, 'max_depth': 4, 'subsample': 0.9959878738508773, 'colsample_bytree': 0.741640493184198, 'min_child_weight': 7}
[0]	validation_0-rmse:1.04631
[100]	validation_0-rmse:0.14471
[200]	validation_0-rmse:0.14784
[300]	validation_0-rmse:0.14979
[400]	validation_0-rmse:0.15062
[500]	validation_0-rmse:0.15075
[528]	validation_0-rmse:0.15076
[0]	validation_0-rmse:0.94138
[100]	validation_0-rmse:0.09140
[200]	validation_0-rmse:0.09115
[300]	validation_0-rmse:0.09172
[400]	validation_0-rmse:0.09118
[500]	validation_0-rmse:0.09124
[528]	validation_0-rmse:0.09120
[0]	validation_0-rmse:0.81409
[100]	validation_0-rmse:0.20207
[200]	validation_0-rmse:0.19814
[300]	validation_0-rmse:0.19941
[400]	validation_0-rmse:0.20017
[500]	validation_0-rmse:0.20138
[528]	validation_0-rmse:0.20127

[I 2026-05-24 21:10:29,435] Trial 12 finished with value: 0.14774466551828194 and parameters: {'n_estimators': 529, 'learning_rate': 0.058870409967848675, 'max_depth': 7, 'subsample': 0.9036308188087117, 'colsample_bytree': 0.7640835394492674, 'min_child_weight': 8}. Best is trial 12 with value: 0.14774466551828194.

Trial 12 | RMSE: 0.1477 | params: {'n_estimators': 529, 'learning_rate': 0.058870409967848675, 'max_depth': 7, 'subsample': 0.9036308188087117, 'colsample_bytree': 0.7640835394492674, 'min_child_weight': 8}
[0]	validation_0-rmse:1.06659
[100]	validation_0-rmse:0.14781
[200]	validation_0-rmse:0.14690
[300]	validation_0-rmse:0.14822
[400]	validation_0-rmse:0.14899
[500]	validation_0-rmse:0.14927
[529]	validation_0-rmse:0.14929
[0]	validation_0-rmse:0.95726
[100]	validation_0-rmse:0.09740
[200]	validation_0-rmse:0.08908
[300]	validation_0-rmse:0.08959
[400]	validation_0-rmse:0.08954
[500]	validation_0-rmse:0.08982
[529]	validation_0-rmse:0.08991
[0]	validation_0-rmse:0.82667
[100]	validation_0-rmse:0.21011
[200]	validation_0-rmse:0.19977
[300]	validation_0-rmse:0.20068
[400]	validation_0-rmse:0.20247
[500]	validation_0-rmse:0.20353
[529]	validation_0-rmse:0.20375

[I 2026-05-24 21:12:09,616] Trial 13 finished with value: 0.14765252166493925 and parameters: {'n_estimators': 530, 'learning_rate': 0.0403598484545884, 'max_depth': 8, 'subsample': 0.8547830215753047, 'colsample_bytree': 0.7424345140952812, 'min_child_weight': 5}. Best is trial 13 with value: 0.14765252166493925.

Trial 13 | RMSE: 0.1477 | params: {'n_estimators': 530, 'learning_rate': 0.0403598484545884, 'max_depth': 8, 'subsample': 0.8547830215753047, 'colsample_bytree': 0.7424345140952812, 'min_child_weight': 5}
[0]	validation_0-rmse:1.09455
[100]	validation_0-rmse:0.31924
[200]	validation_0-rmse:0.16611
[300]	validation_0-rmse:0.14712
[400]	validation_0-rmse:0.14595
[500]	validation_0-rmse:0.14667
[584]	validation_0-rmse:0.14679
[0]	validation_0-rmse:0.97957
[100]	validation_0-rmse:0.28664
[200]	validation_0-rmse:0.11830
[300]	validation_0-rmse:0.09478
[400]	validation_0-rmse:0.09137
[500]	validation_0-rmse:0.09048
[584]	validation_0-rmse:0.09085
[0]	validation_0-rmse:0.84426
[100]	validation_0-rmse:0.34273
[200]	validation_0-rmse:0.23491
[300]	validation_0-rmse:0.21050
[400]	validation_0-rmse:0.20164
[500]	validation_0-rmse:0.19988
[584]	validation_0-rmse:0.19983

[I 2026-05-24 21:14:00,644] Trial 14 finished with value: 0.1458241188188727 and parameters: {'n_estimators': 585, 'learning_rate': 0.014151024758081159, 'max_depth': 8, 'subsample': 0.8587279113760851, 'colsample_bytree': 0.8910281877254501, 'min_child_weight': 8}. Best is trial 14 with value: 0.1458241188188727.

Trial 14 | RMSE: 0.1458 | params: {'n_estimators': 585, 'learning_rate': 0.014151024758081159, 'max_depth': 8, 'subsample': 0.8587279113760851, 'colsample_bytree': 0.8910281877254501, 'min_child_weight': 8}
[0]	validation_0-rmse:1.09651
[100]	validation_0-rmse:0.36492
[200]	validation_0-rmse:0.18796
[300]	validation_0-rmse:0.15736
[400]	validation_0-rmse:0.15220
[500]	validation_0-rmse:0.14966
[600]	validation_0-rmse:0.14819
[614]	validation_0-rmse:0.14811
[0]	validation_0-rmse:0.98103
[100]	validation_0-rmse:0.34732
[200]	validation_0-rmse:0.17405
[300]	validation_0-rmse:0.13775
[400]	validation_0-rmse:0.12751
[500]	validation_0-rmse:0.12450
[600]	validation_0-rmse:0.12321
[614]	validation_0-rmse:0.12322
[0]	validation_0-rmse:0.84546
[100]	validation_0-rmse:0.37646
[200]	validation_0-rmse:0.26392
[300]	validation_0-rmse:0.23737
[400]	validation_0-rmse:0.22779
[500]	validation_0-rmse:0.22434
[600]	validation_0-rmse:0.22247
[614]	validation_0-rmse:0.22255

[I 2026-05-24 21:16:24,388] Trial 15 finished with value: 0.16462484505708438 and parameters: {'n_estimators': 615, 'learning_rate': 0.012410807029560086, 'max_depth': 8, 'subsample': 0.7542826896057571, 'colsample_bytree': 0.9319273447716784, 'min_child_weight': 1}. Best is trial 14 with value: 0.1458241188188727.

Trial 15 | RMSE: 0.1646 | params: {'n_estimators': 615, 'learning_rate': 0.012410807029560086, 'max_depth': 8, 'subsample': 0.7542826896057571, 'colsample_bytree': 0.9319273447716784, 'min_child_weight': 1}
[0]	validation_0-rmse:1.05867
[100]	validation_0-rmse:0.15261
[200]	validation_0-rmse:0.15392
[300]	validation_0-rmse:0.15494
[400]	validation_0-rmse:0.15524
[500]	validation_0-rmse:0.15548
[600]	validation_0-rmse:0.15555
[700]	validation_0-rmse:0.15556
[800]	validation_0-rmse:0.15556
[900]	validation_0-rmse:0.15557
[957]	validation_0-rmse:0.15557
[0]	validation_0-rmse:0.95038
[100]	validation_0-rmse:0.09623
[200]	validation_0-rmse:0.09285
[300]	validation_0-rmse:0.09300
[400]	validation_0-rmse:0.09315
[500]	validation_0-rmse:0.09299
[600]	validation_0-rmse:0.09300
[700]	validation_0-rmse:0.09294
[800]	validation_0-rmse:0.09292
[900]	validation_0-rmse:0.09295
[957]	validation_0-rmse:0.09298
[0]	validation_0-rmse:0.82167
[100]	validation_0-rmse:0.20300
[200]	validation_0-rmse:0.19917
[300]	validation_0-rmse:0.19980
[400]	validation_0-rmse:0.20022
[500]	validation_0-rmse:0.20077
[600]	validation_0-rmse:0.20143
[700]	validation_0-rmse:0.20171
[800]	validation_0-rmse:0.20175
[900]	validation_0-rmse:0.20194
[957]	validation_0-rmse:0.20194

[I 2026-05-24 21:18:50,008] Trial 16 finished with value: 0.15016328902884715 and parameters: {'n_estimators': 958, 'learning_rate': 0.04778897986455923, 'max_depth': 7, 'subsample': 0.8538856947635991, 'colsample_bytree': 0.8883168825174461, 'min_child_weight': 5}. Best is trial 14 with value: 0.1458241188188727.

Trial 16 | RMSE: 0.1502 | params: {'n_estimators': 958, 'learning_rate': 0.04778897986455923, 'max_depth': 7, 'subsample': 0.8538856947635991, 'colsample_bytree': 0.8883168825174461, 'min_child_weight': 5}
[0]	validation_0-rmse:1.06026
[100]	validation_0-rmse:0.14258
[200]	validation_0-rmse:0.14423
[300]	validation_0-rmse:0.14722
[400]	validation_0-rmse:0.14804
[500]	validation_0-rmse:0.14861
[600]	validation_0-rmse:0.14910
[647]	validation_0-rmse:0.14925
[0]	validation_0-rmse:0.95134
[100]	validation_0-rmse:0.09417
[200]	validation_0-rmse:0.09117
[300]	validation_0-rmse:0.09180
[400]	validation_0-rmse:0.09163
[500]	validation_0-rmse:0.09188
[600]	validation_0-rmse:0.09226
[647]	validation_0-rmse:0.09231
[0]	validation_0-rmse:0.82243
[100]	validation_0-rmse:0.20936
[200]	validation_0-rmse:0.20613
[300]	validation_0-rmse:0.20584
[400]	validation_0-rmse:0.20654
[500]	validation_0-rmse:0.20671
[600]	validation_0-rmse:0.20759
[647]	validation_0-rmse:0.20801

[I 2026-05-24 21:21:00,886] Trial 17 finished with value: 0.14985839230921486 and parameters: {'n_estimators': 648, 'learning_rate': 0.046412699594620924, 'max_depth': 9, 'subsample': 0.7438417022597776, 'colsample_bytree': 0.6820945485105195, 'min_child_weight': 8}. Best is trial 14 with value: 0.1458241188188727.

Trial 17 | RMSE: 0.1499 | params: {'n_estimators': 648, 'learning_rate': 0.046412699594620924, 'max_depth': 9, 'subsample': 0.7438417022597776, 'colsample_bytree': 0.6820945485105195, 'min_child_weight': 8}
[0]	validation_0-rmse:0.96626
[100]	validation_0-rmse:0.15350
[200]	validation_0-rmse:0.15387
[300]	validation_0-rmse:0.15384
[400]	validation_0-rmse:0.15384
[401]	validation_0-rmse:0.15384
[0]	validation_0-rmse:0.87562
[100]	validation_0-rmse:0.09157
[200]	validation_0-rmse:0.09303
[300]	validation_0-rmse:0.09314
[400]	validation_0-rmse:0.09313
[401]	validation_0-rmse:0.09313
[0]	validation_0-rmse:0.76411
[100]	validation_0-rmse:0.19722
[200]	validation_0-rmse:0.19896
[300]	validation_0-rmse:0.19922
[400]	validation_0-rmse:0.19920
[401]	validation_0-rmse:0.19922

[I 2026-05-24 21:22:14,618] Trial 18 finished with value: 0.14873322009008524 and parameters: {'n_estimators': 402, 'learning_rate': 0.13409020006888517, 'max_depth': 9, 'subsample': 0.8566996754794194, 'colsample_bytree': 0.9700673291406763, 'min_child_weight': 6}. Best is trial 14 with value: 0.1458241188188727.

Trial 18 | RMSE: 0.1487 | params: {'n_estimators': 402, 'learning_rate': 0.13409020006888517, 'max_depth': 9, 'subsample': 0.8566996754794194, 'colsample_bytree': 0.9700673291406763, 'min_child_weight': 6}
[0]	validation_0-rmse:1.08644
[100]	validation_0-rmse:0.20190
[200]	validation_0-rmse:0.14908
[274]	validation_0-rmse:0.14757
[0]	validation_0-rmse:0.97300
[100]	validation_0-rmse:0.16086
[200]	validation_0-rmse:0.09223
[274]	validation_0-rmse:0.09047
[0]	validation_0-rmse:0.83918
[100]	validation_0-rmse:0.26365
[200]	validation_0-rmse:0.21106
[274]	validation_0-rmse:0.20307

[I 2026-05-24 21:22:59,208] Trial 19 finished with value: 0.14703778530863196 and parameters: {'n_estimators': 275, 'learning_rate': 0.02171831802347411, 'max_depth': 7, 'subsample': 0.8686994908011865, 'colsample_bytree': 0.8801297772476299, 'min_child_weight': 8}. Best is trial 14 with value: 0.1458241188188727.

Trial 19 | RMSE: 0.1470 | params: {'n_estimators': 275, 'learning_rate': 0.02171831802347411, 'max_depth': 7, 'subsample': 0.8686994908011865, 'colsample_bytree': 0.8801297772476299, 'min_child_weight': 8}
Best RMSE: 0.1458241188188727
Best params:
  n_estimators: 585
  learning_rate: 0.014151024758081159
  max_depth: 8
  subsample: 0.8587279113760851
  colsample_bytree: 0.8910281877254501
  min_child_weight: 8

# 7. Final Model Training
Train the final model with best Optuna parameters on the full training set and evaluate on the holdout test set.

In [7]:
final_params = dict(best_params)
final_params.update({
    "random_state": 42,
    "objective": "reg:squarederror",
    "tree_method": "hist",
    "device": "cuda"
})

final_model = XGBRegressor(**final_params)
final_model.fit(X_train, y_train, eval_set=[(X_test, y_test)], verbose=100)

test_pred = final_model.predict(X_test)
rmse = float(np.sqrt(mean_squared_error(y_test, test_pred)))
mae = float(mean_absolute_error(y_test, test_pred))
mape = float(np.mean(np.abs((y_test - test_pred) / y_test.replace(0, np.nan))) * 100)

print(f"RMSE: {rmse:.6f}")
print(f"MAE:  {mae:.6f}")
print(f"MAPE: {mape:.4f}%")

print(f"Retraining on full dataset...")
X_full = pd.concat([X_train, X_test])
y_full = pd.concat([y_train, y_test])
final_model.fit(X_full, y_full, verbose=100)
print("Final model trained on full dataset")



# AUTO SAVE immediately after training
from pathlib import Path
import joblib, json
_save_dir = Path("./")
joblib.dump(final_model, _save_dir / "xgboost_model.pkl")
with open(_save_dir / "xgboost_best_params.json", "w") as f:
    json.dump(best_params, f, indent=2)
with open(_save_dir / "feature_columns.json", "w") as f:
    json.dump(feature_cols, f, indent=2)
print("AUTO SAVED")

[0]	validation_0-rmse:1.61718
[100]	validation_0-rmse:0.70026
[200]	validation_0-rmse:0.45400
[300]	validation_0-rmse:0.41089
[400]	validation_0-rmse:0.40230
[500]	validation_0-rmse:0.40159
[584]	validation_0-rmse:0.40314
RMSE: 0.403140
MAE:  0.327727
MAPE: 34.5491%
Retraining on full dataset...
Final model trained on full dataset
AUTO SAVED

In [8]:
import importlib
import nbformat
importlib.reload(nbformat)
print(nbformat.__version__)

5.10.4

# 8. Feature Importance
Visualize the top 15 most important predictors from the trained XGBoost model.

In [9]:
importance = pd.Series(final_model.feature_importances_, index=feature_cols).sort_values(ascending=False).head(15)

fig_imp = go.Figure(
    go.Bar(
        x=importance.values[::-1],
        y=importance.index[::-1],
        orientation="h",
        marker_color="#2563eb"
    )
)
fig_imp.update_layout(
    title=f"{TICKER} XGBoost Top 15 Feature Importance",
    template="plotly_white",
    xaxis_title="Importance",
    yaxis_title="Feature",
    height=600
)
fig_imp.show()

# 9. Forecast Plot
Plot holdout-period actual vs predicted values and a 30-day future forecast using the latest feature row as a simple forward scenario.

In [10]:
future_steps = 30
last_row = X_test.iloc[[-1]] if len(X_test) > 0 else X_train.iloc[[-1]]
future_X = pd.concat([last_row] * future_steps, ignore_index=True)
future_pred = final_model.predict(future_X)

# Inverse transform to actual prices
try:
    y_test_actual = preprocessor.inverse_transform(y_test.values)
    test_pred_actual = preprocessor.inverse_transform(test_pred)
    future_pred_actual = preprocessor.inverse_transform(future_pred)
except:
    y_test_actual = y_test.values
    test_pred_actual = test_pred
    future_pred_actual = future_pred

if isinstance(test_df.index, pd.DatetimeIndex):
    future_idx = pd.bdate_range(start=test_df.index[-1] + pd.tseries.offsets.BDay(1), periods=future_steps)
else:
    future_idx = pd.RangeIndex(start=len(test_df), stop=len(test_df) + future_steps)

fig_fc = go.Figure()
fig_fc.add_trace(go.Scatter(x=test_df.index, y=y_test_actual, mode="lines", name="Actual", line=dict(color="#111827", width=2)))
fig_fc.add_trace(go.Scatter(x=test_df.index, y=test_pred_actual, mode="lines", name="Predicted", line=dict(color="#2563eb", width=2)))
fig_fc.add_trace(go.Scatter(x=future_idx, y=future_pred_actual, mode="lines", name="30-Day Forecast", line=dict(color="#10b981", width=2, dash="dash")))
fig_fc.update_layout(
    title=f"{TICKER} Actual vs Predicted + 30-Day Forecast",
    template="plotly_white",
    xaxis_title="Date",
    yaxis_title="Close Price (₹)",
    height=600
)
fig_fc.show()

# 10. Save Artifacts
Persist the trained model, preprocessing artifacts, feature columns, and best hyperparameters under the ticker-specific artifacts directory.

In [11]:
model_path = ARTIFACTS_DIR / "xgboost_model.pkl"
feature_cols_path = ARTIFACTS_DIR / "feature_columns.json"
best_params_path = ARTIFACTS_DIR / "xgboost_best_params.json"

joblib.dump(final_model, model_path)
preprocessor.save_artifacts()

with feature_cols_path.open("w", encoding="utf-8") as f:
    json.dump(feature_cols, f, indent=2)

with best_params_path.open("w", encoding="utf-8") as f:
    json.dump(best_params, f, indent=2)

print("Saved artifacts:")
print(f"- Model: {model_path.resolve()}")
print(f"- Preprocessor scaler: {(ARTIFACTS_DIR / 'scaler.pkl').resolve()}")
print(f"- Feature columns: {feature_cols_path.resolve()}")
print(f"- Best params: {best_params_path.resolve()}")

Saved artifacts:
- Model: C:\Users\gaura\Desktop\FinSight\notebooks\models\xgboost\xgboost_model.pkl
- Preprocessor scaler: C:\Users\gaura\Desktop\FinSight\notebooks\models\xgboost\scaler.pkl
- Feature columns: C:\Users\gaura\Desktop\FinSight\notebooks\models\xgboost\feature_columns.json
- Best params: C:\Users\gaura\Desktop\FinSight\notebooks\models\xgboost\xgboost_best_params.json